'\" t
.\"     Title: skytools_upgrade
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 04/01/2014
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "SKYTOOLS_UPGRADE" "1" "04/01/2014" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
skytools_upgrade \- utility for upgrading Skytools code in databases\&.
.SH "SYNOPSIS"
.sp
.nf
skytools_upgrade\&.py [switches] connstr [connstr \&.\&.\&.]
.fi
.SH "DESCRIPTION"
.sp
It connects to given database, then looks for following schemas:
.PP
pgq
.RS 4
Main PgQ code\&.
.RE
.PP
pgq_ext
.RS 4
PgQ batch/event tracking in remote database\&.
.RE
.PP
londiste
.RS 4
Londiste replication\&.
.RE
.sp
If schema exists, its version is detected by querying \&.version() function under schema\&. If the function does not exists, there is some heuristics built in to differentiate between 2\&.1\&.4 and 2\&.1\&.5 version of the schemas\&.
.sp
If detected that version is older than current, it is upgraded by applying upgrade scripts in order\&.
.SH "COMMAND LINE SWITCHES"
.sp
Following switches are common to all skytools\&.DBScript\-based Python programs\&.
.PP
\-h, \-\-help
.RS 4
show help message and exit
.RE
.PP
\-q, \-\-quiet
.RS 4
make program silent
.RE
.PP
\-v, \-\-verbose
.RS 4
make program more verbose
.RE
.PP
\-d, \-\-daemon
.RS 4
make program go background
.RE
.PP
\-\-ini
.RS 4
show commented template config file\&.
.RE
.sp
Following switches are used to control already running process\&. The pidfile is read from config then signal is sent to process id specified there\&.
.PP
\-r, \-\-reload
.RS 4
reload config (send SIGHUP)
.RE
.PP
\-s, \-\-stop
.RS 4
stop program safely (send SIGINT)
.RE
.PP
\-k, \-\-kill
.RS 4
kill program immidiately (send SIGTERM)
.RE
.sp
Options specific to skytools_upgrade:
.PP
\-\-all
.RS 4
Upgrade all databases\&.
.RE
.PP
\-\-not\-really
.RS 4
Don\(cqt actually do anything\&.
.RE
